//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class airline_statistics
    {
        [Display(Name = "Airline identifier")]
        public int id { get; set; }

        [Display(Name = "Airline")]
        public string airline_name { get; set; }

        [Display(Name = "Avg sorties per day")]
        public Nullable<decimal> avg_day_sortie_count { get; set; }
    }
}
