//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class airport
    {
        public airport()
        {
            this.flight_class = new HashSet<flight_class>();
            this.flight_class1 = new HashSet<flight_class>();
            this.department = new HashSet<department>();
            this.employee = new HashSet<employee>();
        }

        [Display(Name = "Airport identifier")]
        public int id { get; set; }
        public int city { get; set; }
        public int airline { get; set; }
    
        public virtual airline airline1 { get; set; }
        public virtual ICollection<flight_class> flight_class { get; set; }
        public virtual ICollection<flight_class> flight_class1 { get; set; }
        public virtual city city1 { get; set; }
        public virtual ICollection<department> department { get; set; }
        public virtual ICollection<employee> employee { get; set; }
    }
}
