//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class brigade
    {
        public brigade()
        {
            this.flight = new HashSet<flight>();
            this.employee = new HashSet<employee>();
        }

        [Display(Name = "Brigade identifier")]
        public int id { get; set; }

        [Display(Name = "Brigade comment")]
        public string comment { get; set; }
    
        public virtual ICollection<flight> flight { get; set; }
        public virtual ICollection<employee> employee { get; set; }
    }
}
