//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class country
    {
        public country()
        {
            this.city = new HashSet<city>();
        }

        [Display(Name = "Country identifier")]
        public int id { get; set; }

        [Display(Name = "Country")]
        public string name { get; set; }
    
        public virtual ICollection<city> city { get; set; }
    }
}
