//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class employee_type
    {
        public employee_type()
        {
            this.department = new HashSet<department>();
            this.employee = new HashSet<employee>();
        }
    
        public int id { get; set; }

        [Display(Name = "Type of employee")]
        public string name { get; set; }
    
        public virtual ICollection<department> department { get; set; }
        public virtual ICollection<employee> employee { get; set; }
    }
}
