//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class flights_by_airline_in_day
    {
        [Display(Name = "Airline identifier")]
        public int id { get; set; }

        [Display(Name = "Airline name")]
        public string airline_name { get; set; }

        [Display(Name = "Date")]
        public Nullable<System.DateTime> sortie { get; set; }

        [Display(Name = "Count of sorties")]
        public long sortie_count { get; set; }
    }
}
