//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class flight_class_stat
    {
        [Display(Name = "Flight class identifier")]
        public int id { get; set; }

        [Display(Name = "Plane identifier")]
        public Nullable<int> plane_id { get; set; }

        [Display(Name = "Plane model identifier")]
        public string plane_model_name { get; set; }

        [Display(Name = "Team identifier")]
        public int team { get; set; }

        [Display(Name = "Avg passenger capacity")]
        public Nullable<decimal> avg_passenger_capacity { get; set; }

        [Display(Name = "Avg tickets bought")]
        public Nullable<decimal> avg_bought { get; set; }

        [Display(Name = "Avg free places")]
        public Nullable<decimal> avg_free { get; set; }

        [Display(Name = "Avg sortie delay")]
        public Nullable<double> avg_sortie_delta_time { get; set; }

        [Display(Name = "Avg landing delay")]
        public Nullable<double> avg_delta_time { get; set; }
    }
}
