//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class flight
    {
        public flight()
        {
            this.sortie = new HashSet<sortie>();
            this.landing = new HashSet<landing>();
        }

        [Display(Name = "Flight identifier")]
        public int id { get; set; }

        public int team { get; set; }
        public int flight_class { get; set; }
        public int plane { get; set; }
    
        public virtual brigade brigade { get; set; }
        public virtual flight_class flight_class1 { get; set; }
        public virtual ICollection<sortie> sortie { get; set; }
        public virtual ICollection<landing> landing { get; set; }
        public virtual plane plane1 { get; set; }
    }
}
