//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class flight_info
    {
        [Display(Name = "Flight identifier")]
        public int id { get; set; }

        [Display(Name = "Plane identifier")]
        public Nullable<int> plane_id { get; set; }

        [Display(Name = "Plane model")]
        public string plane_model_name { get; set; }

        [Display(Name = "Team")]
        public int team { get; set; }

        [Display(Name = "Passenger capacity")]
        public Nullable<short> passenger_capacity { get; set; }

        [Display(Name = "Tickes bought")]
        public long bought { get; set; }

        [Display(Name = "Free places")]
        public Nullable<long> free { get; set; }

        [Display(Name = "Time of sortie")]
        public Nullable<System.DateTime> sortie_start { get; set; }

        [Display(Name = "Sotie delay")]
        public Nullable<System.TimeSpan> sortie_delta_time { get; set; }

        [Display(Name = "Time of landing")]
        public Nullable<System.DateTime> landing_start { get; set; }

        [Display(Name = "Landing delay")]
        public Nullable<System.TimeSpan> landing_delta_time { get; set; }

        [Display(Name = "Flight class identifier")]
        public Nullable<int> flight_class { get; set; }

        [Display(Name = "From")]
        public string from { get; set; }

        [Display(Name = "To")]
        public string to { get; set; }

        [Display(Name = "Type of periodicity")]
        public string periodicity_type { get; set; }

        [Display(Name = "Time of departure")]
        public Nullable<System.TimeSpan> time_of_departure { get; set; }

        [Display(Name = "Time in travel")]
        public Nullable<System.TimeSpan> travel_time { get; set; }

        [Display(Name = "Range")]
        public Nullable<int> range { get; set; }

        [Display(Name = "Type")]
        public string type { get; set; }

        [Display(Name = "Common price")]
        public Nullable<int> common_price { get; set; }

        [Display(Name = "Premium price")]
        public Nullable<int> premium_price { get; set; }

        [Display(Name = "Airline")]
        public string airline_name { get; set; }
    }
}
