//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class landing
    {
        [Display(Name = "Landing identifier")]
        public int id { get; set; }

        [Display(Name = "Flight identifier")]
        public int flight { get; set; }

        [Display(Name = "Landing state")]
        public string state { get; set; }

        [Display(Name = "Landing delay")]
        public Nullable<System.TimeSpan> delta_time { get; set; }

        [Display(Name = "Landing time")]
        public System.DateTime start { get; set; }

        [Display(Name = "Delay reason")]
        public string reason { get; set; }
    
        public virtual flight flight1 { get; set; }
    }
}
