//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class plane_model
    {
        public plane_model()
        {
            this.plane = new HashSet<plane>();
        }

        [Display(Name = "Plane model identifier")]
        public int id { get; set; }

        [Display(Name = "Passenger capacity")]
        public short passenger_capacity { get; set; }

        [Display(Name = "Plane model")]
        public string name { get; set; }
    
        public virtual ICollection<plane> plane { get; set; }
    }
}
