//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class plane_info
    {
        [Display(Name = "Plane identifier")]
        public int id { get; set; }

        [Display(Name = "Airline")]
        public string airline { get; set; }

        [Display(Name = "Passenger capacity")]
        public short passenger_capacity { get; set; }

        [Display(Name = "Plane model")]
        public string model { get; set; }

        [Display(Name = "Date of last repair")]
        public Nullable<System.DateTime> last_repair { get; set; }

        [Display(Name = "Last repair conclusion")]
        public string last_repair_conclusion { get; set; }

        [Display(Name = "Date of last inspection")]
        public Nullable<System.DateTime> last_inspection { get; set; }

        [Display(Name = "Last inspections conclusion")]
        public string last_inspections_conclusion { get; set; }
    }
}
