//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class plane_inspections
    {
        public plane_inspections()
        {
            this.plane_inspections_ended = new HashSet<plane_inspections_ended>();
        }

        [Display(Name = "Plane inspection identifier")]
        public int id { get; set; }

        [Display(Name = "Inspection scheduled date")]
        public System.DateTime scheduled_date { get; set; }

        [Display(Name = "Responsible")]
        public int responsible { get; set; }

        [Display(Name = "comment")]
        public string comment { get; set; }

        [Display(Name = "plane")]
        public int plane { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual plane plane1 { get; set; }
        public virtual ICollection<plane_inspections_ended> plane_inspections_ended { get; set; }
    }
}
