//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class plane_inspections_ended
    {
        [Display(Name = "Ended inspection identifier")]
        public int id { get; set; }
        public int inspection { get; set; }

        [Display(Name = "Inspection end date")]
        public System.DateTime end_date { get; set; }

        [Display(Name = "Conclusion")]
        public string conclusion { get; set; }

        [Display(Name = "Comment")]
        public string comment { get; set; }
    
        public virtual plane_inspections plane_inspections { get; set; }
    }
}
