//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class sortie
    {
        public sortie()
        {
            this.ticket = new HashSet<ticket>();
        }

        [Display(Name = "Sortie identifier")]
        public int id { get; set; }

        public int flight { get; set; }
        public string state { get; set; }

        [Display(Name = "Delay time")]
        public Nullable<System.TimeSpan> delta_time { get; set; }

        [Display(Name = "Starting time")]
        public System.DateTime start { get; set; }

        [Display(Name = "Delay reason")]
        public string reason { get; set; }
    
        public virtual flight flight1 { get; set; }
        public virtual ICollection<ticket> ticket { get; set; }
    }
}
