//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class sorties_with_passengers
    {
        [Display(Name = "Time of sortie")]
        public System.DateTime start { get; set; }

        [Display(Name = "Passanger name")]
        public string name { get; set; }

        [Display(Name = "Passanger lastname")]
        public string lastname { get; set; }

        [Display(Name = "Passanger place")]
        public int place { get; set; }

        [Display(Name = "Passanger count of baggage")]
        public long baggages_count { get; set; }
    }
}
