//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class sorties_in_month
    {
        [Display(Name = "Identifier")]
        public int id { get; set; }

        [Display(Name = "Plane identifier")]
        public Nullable<int> plane_id { get; set; }

        [Display(Name = "Plane model")]
        public string plane_model_name { get; set; }

        [Display(Name = "Team")]
        public int team { get; set; }

        [Display(Name = "Passenger capacity")]
        public Nullable<short> passenger_capacity { get; set; }

        [Display(Name = "Tickets bought")]
        public long bought { get; set; }

        [Display(Name = "Free places")]
        public Nullable<long> free { get; set; }

        [Display(Name = "Sortie")]
        public Nullable<System.DateTime> sortie_start { get; set; }

        [Display(Name = "Sortie delay")]
        public Nullable<System.TimeSpan> sortie_delta_time { get; set; }

        [Display(Name = "Landing")]
        public Nullable<System.DateTime> landing_start { get; set; }

        [Display(Name = "Landing delay")]
        public Nullable<System.TimeSpan> landing_delta_time { get; set; }
    }
}
