//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ticket
    {
        public ticket()
        {
            this.registration = new HashSet<registration>();
        }

        [Display(Name = "Ticket identifier")]
        public int id { get; set; }
        public int flight { get; set; }
        public int owner { get; set; }

        [Display(Name = "Place")]
        public int place { get; set; }
    
        public virtual passenger passenger { get; set; }
        public virtual ICollection<registration> registration { get; set; }
        public virtual sortie sortie { get; set; }
    }
}
